version: "3.8"

services:
  redis_test:
    image: redis
    platform: linux/arm64
    container_name: redis_test
    restart: always
    ports:
      - "63799:6379"
    command: redis-server --appendonly yes

  mysql_test:
    image: mysql
    platform: linux/arm64
    container_name: mysql_test
    restart: always
    ports:
      - "33066:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
