version: "3.8"

services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    command: sh ./start_server.sh
    depends_on:
      - redis_ab180
      - mysql_ab180
    container_name: server
    hostname: server
    restart: always
    ports:
      - "8080:8000"

  redis_ab180:
    image: redis
    platform: linux/arm64
    container_name: redis_ab180
    restart: always
    ports:
      - "6379"
    command: redis-server --appendonly yes

  mysql_ab180:
    image: mysql
    platform: linux/arm64
    container_name: mysql_ab180
    restart: always
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ab180
      - MYSQL_DATABASE=ab180
      - MYSQL_USER=ab180
      - MYSQL_PASSWORD=ab180
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
